plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dep.management)
    alias(libs.plugins.openapi.generator)
}

group = 'com.insurance'
version = '0.0.1-SNAPSHOT'
description = 'Simple project for evaluating a policy based on configured or given DSL'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.java.toolchain.get().toInteger())
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

openApiGenerate {
    generatorName = 'spring'
    inputSpec = "$rootDir/src/main/resources/openapi.yaml"
    outputDir = layout.buildDirectory.dir('generated').get().asFile.toString()
    apiPackage = 'com.insurance.policy_evaluator_dsl.api'
    modelPackage = 'com.insurance.policy_evaluator_dsl.dto'
    generateApiTests = false
    generateModelTests = false
    generateApiDocumentation = true
    generateModelDocumentation = true
    configOptions = [
            interfaceOnly  : 'true',
            useSpringBoot4 : 'true',
            useTags        : 'true',
            openApiNullable: 'false',
            useJakartaEe   : 'true',
    ]
}

sourceSets {
    main {
        java {
            srcDir layout.buildDirectory.dir('generated/src/main/java')
        }
    }
}

compileJava.dependsOn tasks.openApiGenerate
tasks.named('bootRun') { dependsOn tasks.openApiGenerate }

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation libs.springdoc.openapi.webmvc.ui

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
