spring.application.name=policy-evaluator-dsl

# H2
spring.datasource.url=jdbc:h2:mem:policydb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# Default seeded policy
policy.default.name=Standard Policy
policy.default.description=Default policy seeded on startup
policy.default.eligibility-dsl=age >= 18 AND age <= 65 AND claimFreeYears >= 1
policy.default.base-premium=500
policy.default.variable-premium-dsl=(age * 8) - (claimFreeYears * 20)
policy.default.currency=EUR
