[versions]
archunit = "1.4.1"
jqwik = "1.9.3"
java-toolchain = "25"
mapstruct = "1.6.3"
openapi-generator = "7.20.0"
pitest = "1.22.1"
pitest-junit5 = "1.2.3"
rest-assured = "6.0.0"
spring-boot = "4.0.3"
spring-dep-management = "1.1.7"
springdoc = "2.6.0"
lombok = "1.18.42"

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
pitest-command-line = { module = "org.pitest:pitest-command-line", version.ref = "pitest" }
pitest-junit5-plugin = { module = "org.pitest:pitest-junit5-plugin", version.ref = "pitest-junit5" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
springdoc-openapi-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

[plugins]
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dep-management = { id = "io.spring.dependency-management", version.ref = "spring-dep-management" }
